version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certbot.conf:/etc/nginx/conf.d/certbot.conf:ro
      - ./html:/usr/share/nginx/html:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - certbot

  certbot:
    image: certbot/certbot
    container_name: certbot_ssl
    restart: always
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "certbot certonly --webroot --webroot-path /var/www/certbot
      --email sahilchaudhari2405@gmail.com --agree-tos --no-eff-email
      -d thetrektraveller.com -d www.thetrektraveller.com
      --keep-until-expiring"

  certbot-renew:
    image: certbot/certbot
    container_name: certbot_renew
    restart: always
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: ["/bin/sh", "-c"]
    command: "crond -f && certbot renew --quiet && nginx -s reload"
