version: '3.8'

services:
  helloworld:
    container_name: helloworld
    image: crccheck/hello-world
    expose:
      - 8000

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt  # Mount SSL certs
      - ./certbot/www:/var/www/certbot  # Webroot for Certbot challenge

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
certbot:
  image: certbot/certbot
  container_name: certbot
  volumes: 
    - ./certbot/conf:/etc/letsencrypt
    - ./certbot/www:/var/www/certbot
  entrypoint: [ "certbot" ]
  command:
    [
      "certonly",
      "--standalone",
      "--non-interactive",
      "--agree-tos",
      "--email", "sahilchaudhari2405@gmail.com",
      "-d", "thetrektraveller.com"
    ]
