version: '3.8'

services:
  helloworld:
    container_name: helloworld
    image: crccheck/hello-world
    expose:
      - "8000"

  certbot-init:
    image: certbot/certbot
    container_name: certbot-init
    entrypoint: ["/bin/sh", "-c"]
    command: |
      certbot certonly --standalone --email user@gmail.com \
      -d yourdomain.com -d www.yourdomain.com \
      --agree-tos --force-renewal 
      touch /var/www/certbot/done
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
    restart: "no"

  certbot-renew:
    image: certbot/certbot
    container_name: certbot-renew
    entrypoint: ["/bin/sh", "-c"]
    command: |
      while true; do
        certbot renew --webroot -w /var/www/certbot
        sleep 60d
      done
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - nginx
    restart: unless-stopped

  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      certbot-init:
        condition: service_completed_successfully
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt  # Mount SSL certs
      - ./certbot/www:/var/www/certbot  # Webroot for Certbot challenge
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
