version: '3.8'

services:
  helloworld:
    container_name: helloworld
    image: crccheck/hello-world
    expose:
      - "8000"

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - helloworld
      - certbot

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: sh -c "certbot certonly --webroot --webroot-path /var/www/certbot --email sahilchaudhari2405@gmail.com--agree-tos --no-eff-email -d thetrektraveller.com -d www.thetrektraveller.com && nginx -s reload"
