version: "3.8"  # Optional, but recommended

services:
  helloworld:
    container_name: helloworld
    image: crccheck/hello-world
    expose:
      - 8000

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www:/var/www/certbot  # Mount Certbot's webroot to Nginx

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: >
      certonly --webroot -w /var/www/certbot 
      --force-renewal 
      --email sahilchaudhari2405@gmail.com
      --agree-tos 
      -d thetrektraveller.com 
      -d www.thetrektraveller.com
